version: 2
updates:
  - package-ecosystem: 'npm'
    labels: ['dependencies', 'auto-merge-from-default']
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    groups:
      production-dependencies:
        applies-to: version-updates
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      development-dependencies:
        applies-to: version-updates
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-minor']
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
